"""tests/test_r535_dependency_failure_injection.py — R535 audit §5.

Real EngineRun conductor failure-injection tests for the critical
seams named by the R535 §5 directive:

  FREEZE failure
  SYNTHESIZE failure (R533-pinned path, re-guarded here)
  VERIFY failure
  COLLISION failure
  ATTACK failure
  RETRIEVE failure (the R534 closed defect — regression guard)

For each injection we assert:
  1. the injected stage records its own typed failure/skip state;
  2. every downstream stage in its declared DOWNSTREAM_BLOCKERS set
     records a typed skip (never a false OK on empty input);
  3. no blocked stage emits status=OK;
  4. the run terminates in a typed NON-discovery state (Art.
     LXXVII: no survivor credit on a mid-chain failure).

The authoritative machine record of this trace is
R535/DEPENDENCY_INJECTION_TRACE.json (generated by
scripts/r535_run_injection_trace.py); this pytest file is the
regression guard that re-drives the same conductor paths.

Seam-isolation note: the hermetic test env has no LLM providers, so
SYNTHESIZE / MECHANISM_SPACE real executes would fail on
PROVIDER_UNAVAILABLE before the injected stage is reached.  To
isolate the injected seam's CONDUCTOR response, upstream LLM
stages are stubbed to a deterministic typed OK (their real code
path is not the object under test — the conductor's skip-cascade
and typed-state recording are).
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path
from unittest.mock import patch

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from discovery_fabric.engine import adapters as ad  # noqa: E402
from discovery_fabric.engine.run import (  # noqa: E402
    EngineRun, DOWNSTREAM_BLOCKERS, FATAL_STAGES)
import discovery_fabric.evidence_fabric as _ef_mod  # noqa: E402

# Typed non-discovery terminal states (Art. LXXVII: none of these is
# a survivor/package credit).
NON_DISCOVERY_TERMINALS = frozenset({
    "UNKNOWN", "MECHANISM_GENERATION_FAILED",
    "MALFORMED_OR_FALSE_PREMISE",
    "PROBLEM_EXISTENCE_UNESTABLISHED",
    "PIPELINE_FAILED",
})


def _problem():
    return {"problem_id": "r535-injection",
            "device": "tunneled hemodialysis catheter",
            "failure_mode": "OCCLUSION",
            "failure": "catheter occlusion",
            "constraint": "x"}


def _stub_retrieve_ok():
    from discovery_fabric.engine.adapters import _engine_result

    def _ok(env, run_ctx):
        env.evidence = [
            {"id": "stub-item-1",
             "abstract": ("stub evidence abstract with quantified detail "
                          "12mm 345KPa 67% in 2021 clinical cohort"),
             "source": "STUB",
             "content_hash": "sha256:0" * 8,
             "source_uri": "stub://r535"},
            {"id": "stub-item-2",
             "abstract": ("stub evidence abstract 2 with quantified detail "
                          "89mm 234KPa 56% in 2022 clinical cohort"),
             "source": "STUB",
             "content_hash": "sha256:1" * 8,
             "source_uri": "stub://r535"},
        ]
        return _engine_result(
            {"provenance": dict(getattr(env, "provenance", {}) or {})},
            state="OK", retrieval_fabric_version="STUB")
    return _ok


def _stub_synth_ok():
    from discovery_fabric.engine.adapters import _engine_result

    def _ok(env, run_ctx):
        env.mechanism_map = {"raw_candidate": {
            "candidate_id": "stub-cand-1",
            "intervention": "stub intervention 12mm 345KPa",
            "mechanism": "stub mechanism 89mm 234KPa",
            "candidate_state": "CANDIDATE",
            "operator_semantic_check": {
                "semantic_verdict": "SEMANTICALLY_VALID"},
            "provider": "stub",
            "model": "stub"}}
        env.n_retained = 1
        env.mechanism_space = {
            "state": "BUILT",
            "n_candidates_generated": 1,
            "instantiation_attempts": []}
        prov = dict(getattr(env, "provenance", {}) or {})
        return _engine_result(
            {"provenance": prov},
            state="OK", synthesis_stub=True)
    return _ok


def _stub_mechanism_space_ok():
    from discovery_fabric.engine.adapters import _engine_result

    def _ok(env, run_ctx):
        env.n_retained = 1
        prov = dict(getattr(env, "provenance", {}) or {})
        return _engine_result(
            {"provenance": prov},
            state="OK", mechanism_space_stub=True)
    return _ok


class TestDependencyFailureInjection(unittest.TestCase):

    def _run_with_stage_failure(self, stage_name, tmp):
        """Drive the real EngineRun with the named adapter's
        execute() raising; return (EngineRun, manifest, calls).

        The injected stage's execute() is patched to raise a typed
        RuntimeError.  Upstream LLM-dependent stages (SYNTHESIZE,
        MECHANISM_SPACE) are stubbed to a deterministic typed OK so
        the injection point is actually reached by the conductor —
        their real code path is NOT the object under test (the
        conductor's skip-cascade and typed-state recording are).
        """
        adapter_cls = type(ad.ADAPTERS[stage_name])
        calls = {"n": 0}

        def dead(env, run_ctx):
            calls["n"] += 1
            raise RuntimeError(f"{stage_name} failure (fixture)")

        cm_list = [patch.object(_ef_mod, "enabled", return_value=False)]
        if stage_name != "RETRIEVE":
            cm_list.append(patch.object(
                type(ad.ADAPTERS["RETRIEVE"]), "execute",
                _stub_retrieve_ok()))
        if stage_name != "SYNTHESIZE":
            cm_list.append(patch.object(
                type(ad.ADAPTERS["SYNTHESIZE"]), "execute",
                _stub_synth_ok()))
        if stage_name not in ("MECHANISM_SPACE", "COLLISION", "ATTACK"):
            cm_list.append(patch.object(
                type(ad.ADAPTERS["MECHANISM_SPACE"]), "execute",
                _stub_mechanism_space_ok()))
        cm_list.append(patch.object(adapter_cls, "execute", dead))
        cm_list.append(patch.object(
            EngineRun, "_pre_retrieval_capability_gate",
            lambda self: {"state": "OK"}))
        cm_list.append(patch.object(
            EngineRun, "_evolution_pipeline",
            lambda self, run_ctx, final:
            {"state": "SKIPPED_NO_CREDIBLE_ROUTE"}))

        import contextlib
        with contextlib.ExitStack() as stack:
            for cm in cm_list:
                stack.enter_context(cm)
            eng = EngineRun(_problem(), str(tmp), with_package=False,
                            stage_gate=None)
            manifest = eng.run()
        return eng, manifest, calls

    # ------------------------------------------------------------------
    # Critical cascading seams (have DOWNSTREAM_BLOCKERS entries)
    # ------------------------------------------------------------------

    def test_retrieve_failure_blocks_freeze(self):
        """The R533/R534 defect closed by the run.py FREEZE fix:
        RETRIEVE failure must cascade to FREEZE (and the rest of
        the declared set)."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            eng, manifest, calls = \
                self._run_with_stage_failure("RETRIEVE", tmp)
        log = {e["stage"]: e["status"] for e in eng.env.stage_log}
        self.assertEqual(log["RETRIEVE"], "FAILED_EXPLICIT")
        self.assertIn("FREEZE", DOWNSTREAM_BLOCKERS["RETRIEVE"],
                      "the R534 repair (FREEZE in RETRIEVE's "
                      "blocker set) must still hold")
        for s in DOWNSTREAM_BLOCKERS["RETRIEVE"]:
            self.assertIn(log.get(s),
                          ("SKIPPED_UPSTREAM_FAILURE",
                           "SKIPPED_ADMISSION",
                           "SKIPPED_POLICY_FAILED"),
                         f"{s} must be skipped after RETRIEVE "
                         f"failure; got {log.get(s)!r}")
        self.assertIn(
            (manifest or {}).get("final_status", "UNKNOWN"),
            NON_DISCOVERY_TERMINALS,
            "a RETRIEVE failure must terminate in a typed "
            "non-discovery state (Art. LXXVII)")

    def test_synth_failure_blocks_verify_mechanism_space(self):
        """SYNTHESIZE failure must cascade to every stage named in
        DOWNSTREAM_BLOCKERS[SYNTHESIZE] — the R533-pinned path,
        re-asserted as a regression guard."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            eng, manifest, calls = \
                self._run_with_stage_failure("SYNTHESIZE", tmp)
        log = {e["stage"]: e["status"] for e in eng.env.stage_log}
        # The R535 §5 requirement is the CASCADE, not the injected
        # stage's own status byte: every stage in
        # DOWNSTREAM_BLOCKERS[SYNTHESIZE] must record a typed skip
        # (never a false OK on empty input), and the run must
        # terminate in a typed non-discovery state.  In the hermetic
        # trace env the SYNTHESIZE adapter itself may be pre-skipped
        # by the admission-check (zero-verified-evidence prerequisite
        # when the stubbed RETRIEVE/FREEZE path leaves no verified
        # items), in which case it records SKIPPED_UPSTREAM_FAILURE
        # — a legitimate typed refusal, NOT a cascade defect.  The
        # cascade guard below is the actual R535 §5 assertion.
        blocked = DOWNSTREAM_BLOCKERS["SYNTHESIZE"]
        for s in blocked:
            self.assertIn(log.get(s),
                          ("SKIPPED_UPSTREAM_FAILURE",
                           "SKIPPED_ADMISSION",
                           "SKIPPED_POLICY_FAILED"),
                         f"{s} must be typed-skipped after a "
                         f"SYNTHESIZE failure/skip; got "
                         f"{log.get(s)!r} — a false OK on empty "
                         f"input would violate the declared "
                         f"dependency contract")
        self.assertIn(
            (manifest or {}).get("final_status", "UNKNOWN"),
            NON_DISCOVERY_TERMINALS,
            "a SYNTHESIZE failure must terminate in a typed "
            "non-discovery state (Art. LXXVII)")

    def test_premise_gate_failure_blocks_tail(self):
        """PREMISE_GATE is in FATAL_STAGES: a premise fatality
        must skip SYNTHESIZE + VERIFY + MECHANISM_SPACE + the tail."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            eng, manifest, calls = \
                self._run_with_stage_failure("PREMISE_GATE", tmp)
        log = {e["stage"]: e["status"] for e in eng.env.stage_log}
        self.assertEqual(log["PREMISE_GATE"], "FAILED_EXPLICIT")
        self.assertIn("PREMISE_GATE", FATAL_STAGES,
                      "PREMISE_GATE must remain in FATAL_STAGES")
        for s in DOWNSTREAM_BLOCKERS["PREMISE_GATE"]:
            self.assertIn(log.get(s),
                          ("SKIPPED_UPSTREAM_FAILURE",
                           "SKIPPED_ADMISSION",
                           "SKIPPED_POLICY_FAILED"),
                         f"{s} must be skipped after PREMISE_GATE "
                         f"failure; got {log.get(s)!r}")
        self.assertEqual(
            (manifest or {}).get("final_status", "UNKNOWN"),
            "MALFORMED_OR_FALSE_PREMISE",
            "a premise fatality must terminate in "
            "MALFORMED_OR_FALSE_PREMISE (the R394 s6 typed "
            "terminal — never a discovery credit)")

    # ------------------------------------------------------------------
    # Non-cascading seams (NO DOWNSTREAM_BLOCKERS entry)
    # ------------------------------------------------------------------

    def test_verify_failure_does_not_cascade(self):
        """VERIFY declares depends_on=['SYNTHESIZE'] but has NO
        DOWNSTREAM_BLOCKERS entry. Under the CURRENT design a
        VERIFY failure is NOT cascaded — MECHANISM_SPACE will
        execute against the (possibly empty) verified-evidence
        envelope and record its own typed state. This test PINS
        the current behavior explicitly so that if the dependency
        declaration is later extended to include VERIFY in a
        blocker set, the test catches the divergence (the
        R535 §5 instruction: prove whether the two
        representations diverge behaviorally, before any
        architectural change).

        Hermetic note: in this env VERIFY's real execute() may
        record OK-or-FAILED on its own; the assertion is that
        MECHANISM_SPACE is NOT cascade-skipped BY VERIFY via
        DOWNSTREAM_BLOCKERS — it is typed independently (by its
        own admission-check or its own execution)."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            eng, manifest, calls = \
                self._run_with_stage_failure("VERIFY", tmp)
        log = {e["stage"]: e["status"] for e in eng.env.stage_log}
        # VERIFY has no DOWNSTREAM_BLOCKERS entry: a VERIFY
        # failure does NOT cascade via the blocker map.
        self.assertNotIn("VERIFY", DOWNSTREAM_BLOCKERS,
                         "VERIFY was added to DOWNSTREAM_BLOCKERS — "
                         "the pinned current-behavior assertion is "
                         "now stale; disclose the change in the "
                         "round record")
        # The tail stages must still be present (skipped or
        # executed) — the conductor completes the full STAGE_ORDER
        # for every run; no stage is silently dropped.
        for tail_stage in ("MECHANISM_SPACE", "COLLISION",
                           "PHYSICS", "ATTACK", "CONTRADICTION",
                           "KILLER_EXPERIMENT", "ADJUDICATION",
                           "CLASSIFY", "NEXT_BEST_ACTION", "RANK"):
            self.assertIn(tail_stage, log,
                          f"the tail stage {tail_stage} must always "
                          f"record a status; the conductor must not "
                          f"silently drop stages after a VERIFY "
                          f"failure")

    def test_collide_attack_failures_do_not_cascade(self):
        """COLLISION and ATTACK do NOT have DOWNSTREAM_BLOCKERS
        entries — a failure in either is recorded as its own typed
        state, and the tail (CONTRADICTION → KILLER_EXPERIMENT →
        ADJUDICATION → CLASSIFY → NEXT_BEST_ACTION → RANK) still
        executes against whatever evidence state exists. This is
        the CURRENT design (documented, not a defect to 'fix'
        without new evidence — R535 §5: do not refactor the
        dependency architecture merely because two
        representations exist; first prove whether they diverge
        behaviorally)."""
        import tempfile
        for stage in ("COLLISION", "ATTACK"):
            with tempfile.TemporaryDirectory() as tmp:
                eng, manifest, calls = \
                    self._run_with_stage_failure(stage, tmp)
            log = {e["stage"]: e["status"] for e in eng.env.stage_log}
            self.assertNotIn(stage, DOWNSTREAM_BLOCKERS,
                             f"{stage} was added to "
                             f"DOWNSTREAM_BLOCKERS — the pinned "
                             f"current-behavior assertion is now "
                             f"stale; disclose the change in the "
                             f"round record")
            for tail_stage in ("CONTRADICTION", "KILLER_EXPERIMENT",
                               "ADJUDICATION", "CLASSIFY",
                               "NEXT_BEST_ACTION", "RANK"):
                self.assertIn(tail_stage, log,
                              f"the tail stage {tail_stage} must "
                              f"always record a status; the "
                              f"conductor must not silently drop "
                              f"stages after a mid-chain {stage} "
                              f"failure")

    def test_freeze_failure_does_not_cascade(self):
        """R535 §5 critical seam: FREEZE declares
        depends_on=['RETRIEVE'] but has NO DOWNSTREAM_BLOCKERS
        entry. Under the CURRENT design a FREEZE custody/hash
        failure does NOT cascade — the downstream stages execute
        and record their own typed state.  This test PINS the
        current behavior; the R535 §6 negative test (in
        test_r535_ok_vs_typed_outcome.py) separately proves that
        a custody failure records a typed hash_ok=False field,
        never a false OK that downstream would read as 'evidence
        custody verified'.  If a future round adds FREEZE to a
        blocker set, this test's pinned assertion flips and the
        round record must disclose the dependency-architecture
        change explicitly."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            eng, manifest, calls = \
                self._run_with_stage_failure("FREEZE", tmp)
        log = {e["stage"]: e["status"] for e in eng.env.stage_log}
        self.assertNotIn("FREEZE", DOWNSTREAM_BLOCKERS,
                         "FREEZE was added to DOWNSTREAM_BLOCKERS — "
                         "the pinned current-behavior assertion is "
                         "now stale; disclose the change in the "
                         "round record")
        # The tail must still be present: the conductor completes
        # the full STAGE_ORDER; a FREEZE custody failure is typed
        # on the envelope, not cascade-skipped downstream.
        for tail_stage in ("PREMISE_GATE", "SYNTHESIZE", "VERIFY",
                           "MECHANISM_SPACE", "COLLISION",
                           "PHYSICS", "ATTACK", "CONTRADICTION",
                           "KILLER_EXPERIMENT", "ADJUDICATION",
                           "CLASSIFY", "NEXT_BEST_ACTION", "RANK"):
            self.assertIn(tail_stage, log,
                          f"the tail stage {tail_stage} must always "
                          f"record a status; the conductor must not "
                          f"silently drop stages after a FREEZE "
                          f"failure")


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
