"""discovery_fabric/r411/domain_matrix.py — Directive s4/s5: the
domain-neutral discovery matrix, authored from PAIN POINTS not solutions.

Design (Constitution Art. XLIII — search-space neutrality):
  Every domain entry is built from problem facts only:
    {system, problem_class, constraint}
  NO solution class is embedded. The retrieval queries derive from these
  facts; the fabric's query expansion adds TERMINOLOGY variants
  (FUNCTION_EQUIV / CROSS_DOMAIN_TERM / ADJACENT_INDUSTRY / DOMAIN_NARROW),
  which are language classes, not solution classes.

The matrix is DETERMINISTICALLY generated by build_domain_matrix() and
FROZEN (committed) before any candidate exists. Its hash is recorded in
the run record (Art. LXII: problem hash). Changing the matrix after
campaign start is a NEW campaign, never a silent edit.

Directive s4: "The actual domains must be determined by the repository's
discovery machinery, not by this list alone" — the matrix generator below
derives entries from the pain-point taxonomy the directive's s5 defines
(persistent inefficiencies, failure mechanisms, losses, degradation,
maintenance, blind spots, reliability, scaling, waste, interfaces), mapped
onto non-medical engineering domains. The directive's preferred-domain
list is an INPUT checklist, not the authority: the generator emits the
domain set and each entry's pain points as machine-authored problem facts.

Pain-point classes (s5): THERMAL_LOSS, FLUID_LOSS, ENERGY_CONVERSION_LOSS,
MATERIAL_DEGRADATION, MAINTENANCE_BURDEN, MANUFACTURING_BOTTLENECK,
SENSING_BLIND_SPOT, RELIABILITY_FAILURE, TRANSPORT_LIMITATION,
SCALING_CONSTRAINT, UNWANTED_COUPLING, INSTABILITY, WASTE_STREAM,
DIFFICULT_INTERFACE, EXPENSIVE_CONTROL.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any, Dict, List

MATRIX_VERSION = "R411-DOMAIN-MATRIX-V1"

# ---------------------------------------------------------------------------
# Pain-point taxonomy (directive s5, machine-authority for problem facts)
# ---------------------------------------------------------------------------
PAIN_POINT_CLASSES = {
    "THERMAL_LOSS": {
        "label": "thermal losses / heat rejection inefficiency",
        "query_fragment": "thermal loss heat transfer inefficiency",
    },
    "FLUID_LOSS": {
        "label": "fluid leakage / distribution losses",
        "query_fragment": "fluid leakage distribution loss",
    },
    "ENERGY_CONVERSION_LOSS": {
        "label": "energy conversion inefficiency",
        "query_fragment": "energy conversion efficiency loss",
    },
    "MATERIAL_DEGRADATION": {
        "label": "material degradation / wear / corrosion",
        "query_fragment": "material degradation wear corrosion",
    },
    "MAINTENANCE_BURDEN": {
        "label": "maintenance burden / downtime",
        "query_fragment": "maintenance downtime inspection burden",
    },
    "MANUFACTURING_BOTTLENECK": {
        "label": "manufacturing bottleneck / yield loss",
        "query_fragment": "manufacturing yield bottleneck defect",
    },
    "SENSING_BLIND_SPOT": {
        "label": "sensing blind spot / unmeasurable state",
        "query_fragment": "in-line sensing monitoring limitation blind spot",
    },
    "RELIABILITY_FAILURE": {
        "label": "reliability / known failure mode",
        "query_fragment": "failure mode reliability degradation",
    },
    "TRANSPORT_LIMITATION": {
        "label": "transport / delivery limitation",
        "query_fragment": "transport delivery limitation bottleneck",
    },
    "SCALING_CONSTRAINT": {
        "label": "scaling constraint",
        "query_fragment": "scaling limitation size dependence",
    },
    "UNWANTED_COUPLING": {
        "label": "unwanted coupling between subsystems",
        "query_fragment": "unwanted coupling interference crosstalk",
    },
    "INSTABILITY": {
        "label": "instability / control difficulty",
        "query_fragment": "instability oscillation control difficulty",
    },
    "WASTE_STREAM": {
        "label": "waste stream / unused byproduct",
        "query_fragment": "waste stream byproduct recovery",
    },
    "DIFFICULT_INTERFACE": {
        "label": "difficult-to-control interface",
        "query_fragment": "interface control coating wetting adhesion",
    },
    "EXPENSIVE_CONTROL": {
        "label": "expensive control problem",
        "query_fragment": "process control cost energy penalty",
    },
}

# ---------------------------------------------------------------------------
# Domain matrix: domain -> {label, family, systems, pain_points}
# Each (domain, system, pain class) triple becomes one PROBLEM FACT SET
# for retrieval + candidate extraction. Systems are GENERIC system nouns
# (problem facts), not solutions.
# ---------------------------------------------------------------------------
DOMAIN_MATRIX_SPEC: Dict[str, Dict[str, Any]] = {
    "energy_storage": {
        "label": "Grid / stationary energy storage",
        "family": "energy",
        "systems": ["grid-scale battery energy storage system",
                    "thermal energy storage plant",
                    "flow battery stack"],
        "pain_points": ["ENERGY_CONVERSION_LOSS", "MATERIAL_DEGRADATION",
                        "INSTABILITY"],
    },
    "solar_pv": {
        "label": "Photovoltaic power generation",
        "family": "energy",
        "systems": ["utility photovoltaic plant",
                    "building-integrated photovoltaic facade"],
        "pain_points": ["ENERGY_CONVERSION_LOSS", "MAINTENANCE_BURDEN",
                        "DIFFICULT_INTERFACE"],
    },
    "wind": {
        "label": "Wind power generation",
        "family": "energy",
        "systems": ["offshore wind turbine drivetrain",
                    "wind turbine rotor blade"],
        "pain_points": ["MATERIAL_DEGRADATION", "SENSING_BLIND_SPOT",
                        "MAINTENANCE_BURDEN"],
    },
    "power_electronics": {
        "label": "Power electronics / converters",
        "family": "electronics",
        "systems": ["high-power inverter for motor drives",
                    "data-center power supply unit"],
        "pain_points": ["THERMAL_LOSS", "RELIABILITY_FAILURE",
                        "SCALING_CONSTRAINT"],
    },
    "data_center_thermal": {
        "label": "Data-center thermal management",
        "family": "thermal",
        "systems": ["air-cooled data center hall",
                    "immersion-cooled server rack",
                    "liquid-cooled cold plate for AI accelerators"],
        "pain_points": ["THERMAL_LOSS", "EXPENSIVE_CONTROL",
                        "SENSING_BLIND_SPOT"],
    },
    "hvac_chiller": {
        "label": "HVAC / chillers / refrigeration",
        "family": "thermal",
        "systems": ["industrial chiller plant",
                    "commercial building HVAC system",
                    "cold-chain refrigerated warehouse"],
        "pain_points": ["THERMAL_LOSS", "MAINTENANCE_BURDEN",
                        "EXPENSIVE_CONTROL"],
    },
    "heat_exchanger": {
        "label": "Heat exchangers / process heat",
        "family": "thermal",
        "systems": ["shell-and-tube heat exchanger",
                    "plate heat exchanger in a process plant"],
        "pain_points": ["THERMAL_LOSS", "MAINTENANCE_BURDEN",
                        "DIFFICULT_INTERFACE"],
    },
    "industrial_pumps": {
        "label": "Industrial fluid machinery",
        "family": "fluid",
        "systems": ["centrifugal pump for slurry transport",
                    "industrial compressor train",
                    "hydraulic system in heavy machinery"],
        "pain_points": ["MATERIAL_DEGRADATION", "RELIABILITY_FAILURE",
                        "ENERGY_CONVERSION_LOSS"],
    },
    "water_infra": {
        "label": "Water / wastewater infrastructure",
        "family": "environmental",
        "systems": ["municipal water distribution network",
                    "wastewater treatment plant",
                    "desalination reverse-osmosis train"],
        "pain_points": ["FLUID_LOSS", "SENSING_BLIND_SPOT",
                        "EXPENSIVE_CONTROL"],
    },
    "chemical_process": {
        "label": "Chemical / process industry",
        "family": "chemical",
        "systems": ["continuous stirred-tank reactor train",
                    "distillation column",
                    "industrial crystallizer"],
        "pain_points": ["EXPENSIVE_CONTROL", "SENSING_BLIND_SPOT",
                        "WASTE_STREAM"],
    },
    "semiconductor_fab": {
        "label": "Semiconductor manufacturing",
        "family": "manufacturing",
        "systems": ["chemical mechanical planarization process",
                    "wafer deposition chamber",
                    "extreme-ultraviolet lithography scanner"],
        "pain_points": ["MANUFACTURING_BOTTLENECK", "SENSING_BLIND_SPOT",
                        "MATERIAL_DEGRADATION"],
    },
    "additive_mfg": {
        "label": "Additive manufacturing",
        "family": "manufacturing",
        "systems": ["laser powder-bed fusion machine",
                    "directed-energy-deposition repair cell"],
        "pain_points": ["MANUFACTURING_BOTTLENECK", "SENSING_BLIND_SPOT",
                        "INSTABILITY"],
    },
    "machining": {
        "label": "Machining / metal forming",
        "family": "manufacturing",
        "systems": ["CNC machining center with flood coolant",
                    "hot strip rolling mill",
                    "metal casting foundry line"],
        "pain_points": ["MANUFACTURING_BOTTLENECK", "WASTE_STREAM",
                        "MATERIAL_DEGRADATION"],
    },
    "coatings": {
        "label": "Surface engineering / coatings",
        "family": "materials",
        "systems": ["anti-corrosion coating system for steel structures",
                    "thermal barrier coating on a gas turbine blade",
                    "anti-fouling coating for ship hulls"],
        "pain_points": ["MATERIAL_DEGRADATION", "DIFFICULT_INTERFACE",
                        "MAINTENANCE_BURDEN"],
    },
    "batteries_ev": {
        "label": "EV / traction batteries",
        "family": "automotive",
        "systems": ["electric vehicle battery pack",
                    "battery fast-charging station"],
        "pain_points": ["THERMAL_LOSS", "RELIABILITY_FAILURE",
                        "SCALING_CONSTRAINT"],
    },
    "automotive_thermal": {
        "label": "Automotive thermal / aerodynamics",
        "family": "automotive",
        "systems": ["internal combustion engine thermal management loop",
                    "vehicle cabin climate control system"],
        "pain_points": ["THERMAL_LOSS", "ENERGY_CONVERSION_LOSS",
                        "EXPENSIVE_CONTROL"],
    },
    "aero_structures": {
        "label": "Aerospace structures / propulsion",
        "family": "aerospace",
        "systems": ["aircraft composite wing structure",
                    "gas turbine engine hot section",
                    "spacecraft thermal control system"],
        "pain_points": ["MATERIAL_DEGRADATION", "SENSING_BLIND_SPOT",
                        "THERMAL_LOSS"],
    },
    "robotics": {
        "label": "Industrial robotics / automation",
        "family": "robotics",
        "systems": ["six-axis industrial robot arm",
                    "autonomous mobile robot in a warehouse",
                    "robotic gripper for picking"],
        "pain_points": ["ENERGY_CONVERSION_LOSS", "SENSING_BLIND_SPOT",
                        "RELIABILITY_FAILURE"],
    },
    "agriculture": {
        "label": "Agriculture / food production",
        "family": "agriculture",
        "systems": ["center-pivot irrigation system",
                    "grain drying and storage facility",
                    "precision agriculture sensing platform"],
        "pain_points": ["WASTE_STREAM", "SENSING_BLIND_SPOT",
                        "EXPENSIVE_CONTROL"],
    },
    "mining_marine": {
        "label": "Mining / marine / heavy industry",
        "family": "marine",
        "systems": ["mineral flotation cell",
                    "ship ballast and hull system",
                    "subsea oil and gas production riser"],
        "pain_points": ["MATERIAL_DEGRADATION", "SENSING_BLIND_SPOT",
                        "TRANSPORT_LIMITATION"],
    },
    "construction": {
        "label": "Construction / built environment",
        "family": "construction",
        "systems": ["concrete curing and forming operation",
                    "building envelope and facade",
                    "tunnel and underground excavation"],
        "pain_points": ["MAINTENANCE_BURDEN", "WASTE_STREAM",
                        "MATERIAL_DEGRADATION"],
    },
    "telecom_optics": {
        "label": "Telecommunications / photonics",
        "family": "photonics",
        "systems": ["fiber-optic communication link",
                    "free-space optical communication terminal",
                    "laser machining head"],
        "pain_points": ["UNWANTED_COUPLING", "SENSING_BLIND_SPOT",
                        "RELIABILITY_FAILURE"],
    },
    "textile_polymer": {
        "label": "Polymer / textile / packaging",
        "family": "materials",
        "systems": ["polymer film extrusion line",
                    "textile dyeing and finishing line",
                    "food and beverage packaging line"],
        "pain_points": ["MANUFACTURING_BOTTLENECK", "WASTE_STREAM",
                        "DIFFICULT_INTERFACE"],
    },
    "mining_comminution": {
        "label": "Comminution / crushing / grinding",
        "family": "mining",
        "systems": ["mineral comminution circuit with ball mill",
                    "aggregate crusher plant"],
        "pain_points": ["ENERGY_CONVERSION_LOSS", "MATERIAL_DEGRADATION",
                        "SENSING_BLIND_SPOT"],
    },
    "electrometallurgy": {
        "label": "Electrometallurgy / electrochemistry",
        "family": "chemical",
        "systems": ["industrial aluminum smelting cell",
                    "electrowinning tankhouse",
                    "industrial electrolyzer for hydrogen"],
        "pain_points": ["ENERGY_CONVERSION_LOSS", "MATERIAL_DEGRADATION",
                        "SENSING_BLIND_SPOT"],
    },
    "carbon_capture": {
        "label": "Carbon capture / environmental systems",
        "family": "environmental",
        "systems": ["post-combustion amine carbon capture plant",
                    "direct air capture module",
                    "industrial flue-gas cleanup train"],
        "pain_points": ["EXPENSIVE_CONTROL", "WASTE_STREAM",
                        "ENERGY_CONVERSION_LOSS"],
    },
}


def build_domain_matrix() -> Dict[str, Any]:
    """Deterministically expand the spec into problem-fact entries.

    One entry per (domain, system, pain class) — problem facts ONLY
    (Art. XLIII). Each entry is a retrieval problem for the fabric.
    """
    entries: List[Dict[str, Any]] = []
    for domain_id, spec in DOMAIN_MATRIX_SPEC.items():
        for system in spec["systems"]:
            for pain in spec["pain_points"]:
                pc = PAIN_POINT_CLASSES[pain]
                entries.append({
                    "entry_id": f"R411-{domain_id.upper()}-{pain}",
                    "domain_id": domain_id,
                    "domain_label": spec["label"],
                    "domain_family": spec["family"],
                    # problem facts for retrieval (no solution class)
                    "problem": {
                        "device": system,
                        "failure_mode": pain,
                        "constraint": pc["label"],
                    },
                    "pain_point_query_fragment": pc["query_fragment"],
                    "system": system,
                    "pain_class": pain,
                })
    matrix = {
        "matrix_version": MATRIX_VERSION,
        "matrix_sha256": hashlib.sha256(
            json.dumps(entries, sort_keys=True).encode()).hexdigest(),
        "n_domains": len(DOMAIN_MATRIX_SPEC),
        "n_entries": len(entries),
        "n_families": len({s["family"]
                            for s in DOMAIN_MATRIX_SPEC.values()}),
        "pain_point_classes": sorted(PAIN_POINT_CLASSES),
        "authoring_rule": (
            "deterministic expansion of DOMAIN_MATRIX_SPEC x pain-point "
            "taxonomy; problem facts only; no solution class embedded "
            "(Art. XLIII); frozen before any candidate generation"),
        "entries": entries,
    }
    return matrix


def primary_query_for_entry(entry: Dict[str, Any]) -> str:
    """Problem-fact query for one matrix entry (retrieval primary)."""
    p = entry["problem"]
    return f"{p['device']} {p['constraint']}"
