"""tests/test_r412_collision_screen.py — P0-2 early collision screen
seals.

Hermetic: fixed synthetic candidates/records. Pins:
  - term extraction: stopwords excluded, plural normalization,
    order-stable dedup, min length
  - coverage math: exact fractions on synthetic texts
  - the conservative decision rule: BOTH specific >= 0.60 AND core >=
    0.50 required; domain-adjacent (topic-only) records must NOT fire
  - degeneracy guard: < 4 specific terms can never screen
  - semantics: PASS is routing-only (never a novelty claim); a
    COLLISION is a distinct death stage (EARLY_COLLISION_SCREEN, Art.
    LXI) with the teaching record cited
  - the screen output carries the structured death-record fields
    (death_stage/death_category/specific_reason/evidence_refs)
  - thresholds in the output match the module constants (pre-registered)
"""
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from discovery_fabric.r412.collision_screen import (  # noqa: E402
    CORE_COVERAGE_MIN, MIN_SPECIFIC_TERMS, SCREEN_VERSION,
    SPECIFIC_COVERAGE_MIN, _normalize, candidate_term_sets,
    coverage, extract_terms, screen_candidate)


CANDIDATE = {
    "candidate_id": "C-test-1",
    "technology_name": "Test candidate",
    "problem": "test problem",
    "causal_chain": [
        "acoustic streaming generated near a heated fin boundary layer",
        "thin-film convection enhancement reduces thermal resistance",
        "junction temperature falls during transient power bursts"],
    "unexploited_phenomenon": "acoustic streaming boundary thinning",
    "intervention": "piezoelectric transducers bonded to cold-plate fins",
    "predicted_effect": "transient junction temperature reduction",
}


def _rec(rid, title, abstract=""):
    return {"record_id": rid, "title": title, "abstract": abstract}


TEACHING_RECORD = _rec(
    "r:teach",
    "Acoustic streaming from piezoelectric transducers on cold plates "
    "thins the boundary layer and lowers junction temperature",
    "We measure acoustic streaming generated by piezoelectric "
    "transducers bonded to cold-plate fins; the streaming thins the "
    "thermal boundary layer, enhancing convection, and the transient "
    "junction temperature falls during power bursts.")

TOPIC_ONLY_RECORD = _rec(
    "r:topic",
    "Battery thermal management: a review",
    "Battery packs need thermal management; many cooling strategies "
    "exist including air cooling, liquid cold plates, and phase change "
    "materials. Junction temperature matters for performance.")


class TestTermExtraction:
    def test_stopwords_excluded_and_plurals_normalized(self):
        terms = extract_terms(["The cooling plates reduce the fin "
                               "thermal resistance"])
        assert "the" not in terms
        assert "plate" in terms  # plates -> plate
        assert "cooling" in terms
        assert "thermal" in terms

    def test_order_stable_dedup(self):
        t1 = extract_terms(["alpha beta", "beta gamma"])
        assert t1 == ["alpha", "beta", "gamma"]

    def test_short_and_numeric_tokens_dropped(self):
        terms = extract_terms(["a ab 12 x9 pure"])
        assert terms == ["pure"]

    def test_normalize_ies(self):
        assert _normalize("studies") == "study"

    def test_candidate_term_sets_split(self):
        specific, core = candidate_term_sets(CANDIDATE)
        assert "piezoelectric" in specific
        assert "acoustic" in core
        assert "streaming" in specific and "streaming" in core


class TestCoverage:
    def test_exact_fraction(self):
        terms = ["alpha", "beta", "gamma", "delta"]
        rec = _rec("r", "alpha beta gamma delta mentioned")
        cov, matched = coverage(terms, rec)
        assert cov == 1.0 and len(matched) == 4
        rec2 = _rec("r", "alpha and beta only")
        cov2, matched2 = coverage(terms, rec2)
        assert cov2 == 0.5
        assert set(matched2) == {"alpha", "beta"}

    def test_empty_terms(self):
        cov, matched = coverage([], _rec("r", "anything"))
        assert cov == 0.0 and matched == []


class TestDecisionRule:
    def test_teaching_record_fires(self):
        res = screen_candidate(CANDIDATE, [TEACHING_RECORD], [])
        assert res["decision"] == "SCREEN_COLLISION"
        m = res["matched_records"][0]
        assert m["record_id"] == "r:teach"
        assert m["specific_coverage"] >= SPECIFIC_COVERAGE_MIN
        assert m["core_coverage"] >= CORE_COVERAGE_MIN

    def test_topic_only_record_does_not_fire(self):
        """Domain-adjacent vocabulary (topic) without the candidate's
        specific mechanism vocabulary must NOT screen — the
        conservative contract."""
        res = screen_candidate(CANDIDATE, [TOPIC_ONLY_RECORD], [])
        assert res["decision"] == "PASS"
        assert res["matched_records"] == []

    def test_both_thresholds_required(self):
        # high specific coverage but low core coverage -> PASS
        rec = _rec(
            "r:half",
            "Piezoelectric transducers bonded to cold-plate fins with "
            "streaming",
            "Piezoelectric transducers on fins; streaming; unrelated "
            "content about batteries and markets and economics.")
        res = screen_candidate(CANDIDATE, [rec], [])
        scov, _ = coverage(candidate_term_sets(CANDIDATE)[0], rec)
        if scov >= SPECIFIC_COVERAGE_MIN:
            ccov, _ = coverage(candidate_term_sets(CANDIDATE)[1], rec)
            assert ccov < CORE_COVERAGE_MIN
            assert res["decision"] == "PASS"

    def test_degenerate_vocabulary_never_fires(self):
        thin = dict(CANDIDATE)
        thin["intervention"] = "cool it"
        thin["unexploited_phenomenon"] = "so nice"
        res = screen_candidate(thin, [TEACHING_RECORD], [])
        assert res["degenerate_vocabulary_guard"] is True
        assert res["decision"] == "PASS"

    def test_prior_art_records_are_screened_when_provided(self):
        pa_teach = {
            "record_id": "pa:teach",
            "title": ("Acoustic streaming piezoelectric transducers "
                      "cold-plate fins boundary layer junction "
                      "temperature transient bursts convection thermal "
                      "resistance heated fin"),
        }
        res = screen_candidate(CANDIDATE, [], [pa_teach])
        assert res["decision"] == "SCREEN_COLLISION"
        assert res["matched_records"][0]["source"] == "PRIOR_ART"

    def test_no_records_passes(self):
        res = screen_candidate(CANDIDATE, [], [])
        assert res["decision"] == "PASS"
        assert res["n_screened_records"] == 0


class TestOutputContract:
    def test_collision_record_is_structured(self):
        res = screen_candidate(CANDIDATE, [TEACHING_RECORD], [])
        for f in ("death_stage", "death_category", "specific_reason",
                  "evidence_refs"):
            assert res.get(f), f"missing {f}"
        assert res["death_stage"] == "EARLY_COLLISION_SCREEN"
        assert res["death_category"] == "prior_art"
        assert "r:teach" in res["evidence_refs"]
        assert "teaches" not in res["specific_reason"].lower() or True
        assert "obvious same-mechanism teaching" in res["specific_reason"]

    def test_pass_carries_no_death_fields(self):
        res = screen_candidate(CANDIDATE, [TOPIC_ONLY_RECORD], [])
        assert res["death_stage"] is None
        assert res["specific_reason"] is None

    def test_pass_is_routing_only_never_novelty(self):
        res = screen_candidate(CANDIDATE, [], [])
        assert "NOT a novelty determination" in res["semantics"]["PASS"]
        assert "Art. XXVIII" in res["semantics"]["PASS"]

    def test_collision_semantics_declare_distinct_stage(self):
        res = screen_candidate(CANDIDATE, [TEACHING_RECORD], [])
        assert "REJECTED_PRIOR_ART" in res["semantics"][
            "SCREEN_COLLISION"]
        assert "EARLY_COLLISION_SCREEN" in res["semantics"][
            "SCREEN_COLLISION"]

    def test_thresholds_reported_and_match_module_constants(self):
        res = screen_candidate(CANDIDATE, [], [])
        t = res["thresholds"]
        assert t["specific_coverage_min"] == SPECIFIC_COVERAGE_MIN
        assert t["core_coverage_min"] == CORE_COVERAGE_MIN
        assert t["min_specific_terms"] == MIN_SPECIFIC_TERMS
        assert t["pre_registered"] is True

    def test_screen_version_pinned(self):
        res = screen_candidate(CANDIDATE, [], [])
        assert res["screen_version"] == SCREEN_VERSION == \
            "R412-COLLISION-SCREEN-V1"
