"""visual_set.py — R443 the canonical visual-set ladder.

Workstream 2 (operator directive R443-C2): a visual gate must not
declare the visual set complete merely because hero/poster/GLB passed.
The REQUIRED R441 set is explicit, the gate distinguishes

    COMPLETE_PASS / PARTIAL / NOT_RUN / FAIL

and for a package that requires the full visual ladder:

    missing required visual artifact -> NOT_COMPLETE -> no visual release

The ladder lives here — ONE definition shared by the compiler (which
inventories what was produced) and the gate (which re-verifies from
disk, Art. III: the verifier re-derives the claim). The exploded pair
is CONDITIONAL: a single-part architecture has nothing to separate —
its waiver is TYPED and disclosed (reason recorded), never silently
absent (Art. XXV: unknown/absent stays explicit).
"""
from __future__ import annotations

from typing import Any, Dict, List

DEFAULT_TURNTABLE_FRAMES = 12

# the unconditional ladder (R441 directive table, now enforced as a set)
UNCONDITIONAL: tuple = (
    "hero.png",
    "hero.glb",
    "poster.png",
    "dimension.png",
    "section.png",
    "orthographic/front.png",
    "orthographic/side.png",
    "orthographic/top.png",
    "orthographic/iso.png",
)
# frames generated by name pattern
TURNTABLE_PATTERN = "turntable/frame-{n:02d}.png"
# the conditional pair (multi-part architectures only)
CONDITIONAL: tuple = ("exploded.png", "exploded.glb")


def required_artifacts(node_count: int,
                       turntable_frames: int = DEFAULT_TURNTABLE_FRAMES,
                       ) -> Dict[str, Any]:
    """The required ladder for one compile: unconditional artifacts +
    the turntable frames + the conditional exploded pair (required iff
    node_count >= 2, waived with reason otherwise)."""
    req = list(UNCONDITIONAL)
    req += [TURNTABLE_PATTERN.format(n=i) for i in
            range(1, int(turntable_frames) + 1)]
    waived: List[Dict[str, str]] = []
    if node_count >= 2:
        req += list(CONDITIONAL)
    else:
        for name in CONDITIONAL:
            waived.append({
                "artifact": name,
                "reason": ("single-part architecture: nothing to "
                           "separate — typed waiver, disclosed "
                           "(Art. XXV)")})
    return {"required": req, "waived": waived}


def classify(out_dir: str,
             node_count: int,
             turntable_frames: int = DEFAULT_TURNTABLE_FRAMES,
             ) -> Dict[str, Any]:
    """Re-verify the ladder FROM DISK (the gate's own eyes, Art. III):
    which required artifacts exist (non-empty), which are missing,
    which are waived. `complete` is TRUE only when every required
    artifact is present."""
    from pathlib import Path
    spec = required_artifacts(node_count, turntable_frames)
    root = Path(out_dir)
    present: List[str] = []
    missing: List[str] = []
    for name in spec["required"]:
        p = root / name
        if p.is_file() and p.stat().st_size > 0:
            present.append(name)
        else:
            missing.append(name)
    return {
        "required_count": len(spec["required"]),
        "present_count": len(present),
        "present": present,
        "missing": missing,
        "waived": spec["waived"],
        "complete": not missing,
    }
