"""r384_narratives — per-package evidence-card narratives for the
REMEDIATION_3D_AUDIT_RESPONSE report. English, ASCII-safe."""

NARRATIVES = {
    "01_multisegment_flow_control": (
        "The parametric model is a 2.6 mm OD, 120 mm extruded catheter body "
        "with a central 1.2 mm drainage lumen, carrying six flow-sensor "
        "collars (3.0 mm OD, 1.5 mm wide) at the segment boundaries - the "
        "occlusion-locating instrument of the Bayesian inference claim. The "
        "invention-critical geometry is the ring-to-body stack: each collar "
        "rides on the body with a 0.25 mm radial step, so the transverse "
        "section coupon cuts through body lumen AND collar annulus in one "
        "face, and the longitudinal section shows the recorded 20 mm "
        "segment pitch directly. The independent regeneration reproduced "
        "the shipped volume and bounding box exactly, and all six "
        "parameters are linearly traceable to measured features (radii, "
        "bbox extents). What remains MODELLED, not measured, is the sensor "
        "electronics the collars stand for; the geometry is the mounting "
        "envelope, honestly labeled as such in the object roles."),
    "02_adaptive_valve": (
        "The model carries three parts: a 12 mm OD x 20 mm valve housing "
        "with a 1.2 mm axial flow bore and a conical seat pocket; a conical "
        "poppet element that presses into the seat cone in the sealed "
        "state; and a 7 mm actuator cartridge seat recording the actuator "
        "candidate volume. The invention-critical section is the "
        "longitudinal cut through bore, seat cone and poppet - it exposes "
        "the sealing interface the postural regulation claim depends on - "
        "and the transverse cut through the cartridge plane shows the "
        "annular actuator pocket around the bore. Four of five parameters "
        "map to measured features; the poppet geometry is generated from "
        "the conical relation, which is why its parameters are recorded as "
        "non-linearly bound. Tolerances remain UNKNOWN pending a molder "
        "Cpk study, exactly as the dossier states."),
    "03_catalytic_clearance": (
        "The geometry is the contact-time reactor itself: a 2.6 mm OD, "
        "110 mm catheter substrate tube whose 1.3 mm lumen is lined by a "
        "0.02 mm NEP-immobilized enzyme coating annulus. The "
        "invention-critical section is the transverse coupon: it cuts "
        "substrate wall and coating in one face, making the 20 micron "
        "enzyme layer - the entire residence-time mechanism - inspectable "
        "as an annulus in the STEP B-rep, with measured radii 0.652 mm "
        "over 0.63 mm confirming the layer thickness on the built solid. "
        "The coating thickness parameter is bound non-linearly through the "
        "two radii and is recorded that way in the parameter-feature log. "
        "Catalytic activity itself is NOT claimed here; only the geometry "
        "that would deliver it to a bonding vendor."),
    "04_drainage_floor": (
        "The package's single object is the passive dual-lumen safety "
        "floor: a 3.0 mm OD, 100 mm extrusion with a 1.1 mm primary lumen "
        "offset from a 0.6 mm floor lumen, the eccentricity being the "
        "differential-obstruction mechanism. The transverse section coupon "
        "is the definitive evidence view - both lumens appear on one cut "
        "face (verified by independent image inspection) - and the "
        "longitudinal section shows the two channels running full length "
        "with the measured 0.2 mm minimum wall from the built solid. "
        "Regeneration from the shipped parametric source reproduced the "
        "shipped 583.550835 mm3 volume exactly; four of five parameters "
        "map to measured radii and extents, the floor offset being bound "
        "through the containment-wall relation. This is the portfolio's "
        "simplest physics and its most directly auditable CAD."),
    "05_phage_antibiofilm": (
        "The model is a three-layer catheter wall: the 2.6 mm substrate "
        "tube, a 0.05 mm electrospun titanium coating annulus, and a "
        "0.02 mm phage-immobilization matrix annulus lining the 1.4 mm "
        "lumen. The invention-critical geometry is exactly this concentric "
        "stack, and the transverse coupon cuts all three annuli in one "
        "face; the measured radii (0.705 / 0.652 / 0.63 mm) sit on the "
        "built solid at the recorded thicknesses. Three of five parameters "
        "map linearly; the two coating thicknesses are expressed through "
        "radius pairs and recorded as such. The biology - phage viability "
        "and anti-biofilm efficacy - remains an unverified claim of the "
        "dossier; what is shipped is the manufacturing geometry a coating "
        "vendor would receive."),
    "06_failure_predictor": (
        "No 3D artifacts are shipped for this package, and the audit's "
        "footnote anticipated exactly this resolution: the package's own "
        "record classifies it 3D_NOT_APPLICABLE on four measured grounds - "
        "zero geometry-class critical parameters, an empty BOM, no "
        "manufacturing process, and physical-named subsystems that are "
        "input interfaces of a computational system, not geometry the "
        "buyer builds as this technology. The classification is "
        "SOURCE_DERIVED, recorded in MODEL/3D_DESIGN_STATUS.json with the "
        "policy line: do not invent geometry where the technology does "
        "not require it. In a device portfolio context the audit graded "
        "this D; the correct reading is that its deliverables are "
        "software artifacts, and its engineering evidence lives in the "
        "equation registry and dataset roadmap, not in CAD."),
    "07_self_powered_sensing": (
        "The model is a classical bimorph piezoelectric cantilever: two "
        "0.1 mm piezo laminae (20 mm x 4 mm), a 3 mm proof mass at the "
        "tip, and a clamp anchor at the fixed end - the complete "
        "harvester envelope the record's power budget depends on. The "
        "longitudinal section exposes the lamina stack and mass position; "
        "the transverse cut through the tip shows the mass footprint over "
        "the beam width. All four geometry parameters map to measured "
        "extents on the rebuilt solid. The piezoelectric output itself "
        "stays a MODELLED relation in the equation registry (the audit's "
        "piezo-bound equation); the CAD is the mounting and laminate "
        "geometry, which is what a MEMS vendor would be asked to build."),
    "08_nir_photovoltaic": (
        "The model carries the full receiver stack: a 7.0 mm GaAs "
        "photovoltaic die (0.3 mm thick), its carrier substrate, and a "
        "hermetic encapsulation cap with a 0.45 mm optical standoff over "
        "the active face. The invention-critical section is the "
        "longitudinal cut through the stack axis - it shows the cell / "
        "substrate / cap sandwich and the standoff gap that sets the "
        "optical path - while the transverse cut confirms the concentric "
        "disc alignment. Regeneration is exact and the watertight check "
        "passes independently on all three STL derivatives. The optical "
        "power budget remains an analytical claim (PV power equation in "
        "the registry); the geometry shipped is the implant envelope an "
        "optoelectronic vendor would populate."),
    "09_uwb_localization": (
        "The model has two objects: a 2.0 mm OD x 30 mm implant body with "
        "a 0.9 mm drainage lumen, and the helical conductor (0.18 mm wire, "
        "0.45 mm pitch) wound into its surface - the antenna is the RF "
        "invention geometry. The antenna mesh is deliberately dense "
        "(605,108 triangles, watertight per the independent trimesh "
        "check), so its B-rep transverse section solid ships as a compact "
        "509 KB STEP, while the longitudinal B-rep cut of the helical "
        "sweep fragments beyond the 20 MB deliverable budget and is "
        "omitted with the measured reason recorded, replaced by an open "
        "mesh half-shell at the same plane. Both section renders include "
        "the antenna. The SAR-bounded positioning claim stays analytical; "
        "the antenna geometry is now inspectable at RF scale, which is "
        "precisely what the audit demanded."),
    "10_catheter_navigation": (
        "The model is the steerable segment itself: a 2.6 mm OD, 60 mm "
        "multi-lumen body with a 1.2 mm central drainage lumen and three "
        "0.35 mm steering lumens at 120-degree spacing on a 0.95 mm "
        "offset radius. The invention-critical geometry is that "
        "four-lumen cross-section - the actuation asymmetry - and the "
        "transverse section coupon cuts it in a single face with all four "
        "lumens visible (measured radii 0.175 x3 and 0.6 mm on the built "
        "solid). Four of five parameters map linearly to measured "
        "features; the steering offset is bound through the containment "
        "relation. Control electronics and human-in-the-loop autonomy "
        "remain dossier claims; the steering geometry is delivered as "
        "kernel solids a tubing vendor can quote against."),
    "11_gravity_damper": (
        "The model carries the two parts that make the damping element: "
        "an 8 mm OD x 25 mm housing cup with a 5.0 mm coaxial bore and "
        "axial inlet port, and an annular spool riding in the bore whose "
        "0.18 mm annular gap IS the damping element - the audit's 'damper "
        "mechanism is geometric by definition' test. The transverse "
        "section cut through the bore shows housing wall, annular gap and "
        "spool in one face; the longitudinal section exposes the spool "
        "travel length and the inlet port through the housing floor. "
        "Regeneration is exact, both STLs pass the independent watertight "
        "check, and five of six parameters map to measured features. The "
        "damping coefficient relation remains analytical (Poiseuille "
        "family in the equation registry); the gap geometry it depends on "
        "is now measured on the shipped solid."),
    "12_osmotic_valve": (
        "The model is the four-part osmotic regulator: a 10 mm OD "
        "two-chamber housing with an 8 mm through bore, the 0.08 mm "
        "semipermeable membrane disc press-sealed across the bore, and "
        "upper and lower clamp rings that trap the membrane edge. The "
        "invention-critical section is the longitudinal cut on the "
        "chamber axis - it exposes the membrane dividing CSF chamber from "
        "osmotic chamber, the entire mechanism - and the transverse cut "
        "through the clamping plane shows the ring / membrane / bore "
        "stack. Regeneration is exact and six of six parameters map "
        "linearly to measured features. Osmotic flux remains an equation "
        "in the registry; the membrane-and-chamber geometry a machinist "
        "or microfab vendor would receive is delivered as B-rep solids."),
    "13_pressure_sensor": (
        "The model carries the self-referencing bridge geometry: the "
        "active sensor die (etched cavity over a 0.07 mm diaphragm), the "
        "solid reference die that is the R1 design fix, and the carrier "
        "platform bonding both for catheter integration. The "
        "invention-critical section is the transverse cut through the "
        "die plane - it shows cavity versus solid reference die, the "
        "differential structure the self-referencing claim rests on - "
        "and the longitudinal cut shows the two dies on the carrier. All "
        "six parameters were checked against measured features: the "
        "diaphragm and cavity widths are bound through the die "
        "subtractions and are recorded as non-linear by construction. "
        "Piezoresistive response remains analytical; the die and carrier "
        "geometry is what a MEMS foundry would be asked to replicate."),
    "14_acoustic_detection": (
        "The model is the instrumented catheter tip: a 2.0 mm OD x 25 mm "
        "tip body with drainage lumen and a recessed transducer pocket at "
        "the distal face, a 1.7 mm PZT disc press-fit in that pocket "
        "annular to the lumen, and a 0.08 mm acoustic window cap sealing "
        "it. The invention-critical section is the transverse coupon "
        "through the distal face: lumen, PZT annulus and window cap "
        "appear in one cut face, which is the acoustic path geometry the "
        "obstruction-detection claim depends on. Regeneration is exact, "
        "the STLs pass the independent watertight check, and six of six "
        "parameters map linearly to measured features - the cleanest "
        "parameter-to-geometry traceability in the portfolio. Acoustic "
        "discrimination performance remains a dossier-level claim."),
    "15_mr_flow_sensor": (
        "The model carries the four parts of the catheter-scale MR flow "
        "sensor: the 2.0 mm flow tube with a 1.05 mm lumen, the RF coil "
        "annulus around the sensing section, and the two half-annular "
        "magnet segments that are the B0 source. The invention-critical "
        "geometry is the transverse cut at the sensing section - flow "
        "lumen, coil annulus and magnet half-annuli in one face, i.e. the "
        "entire MR-compatible assembly at catheter scale - and the "
        "longitudinal section shows the proximal / distal magnet "
        "placement along the tube. Regeneration is exact; five of seven "
        "parameters map linearly (the magnet half-annulus geometry is "
        "constructed, recorded non-linear). MR flow quantification stays "
        "analytical; the geometry an MR-component vendor would receive is "
        "shipped as kernel solids."),
}
