"""
pathway.py — CEO R374-6: preserve the failed-candidate pathway.

Required pathway for ANY candidate generated by the discovery engine
that fails:

    CANDIDATE -> FAILURE REASON -> EVIDENCE -> ATTACK RESULTS ->
    KILL CONDITION -> CEMETERY

Rules:
  * Nothing is deleted. The cemetery is append-only: no entry may ever
    disappear (mechanically verified against git history), and
    entry_count never decreases.
  * Legacy entries (26 at R374 time) predate the structured schema.
    Their pathway is re-presented from RECORDED fields only:
    KILL_CONDITION is derived from the recorded kill_reason (+ recorded
    physical_constraint where present) and marked as a derivation —
    never as new evidence; ATTACK_RESULTS that were never structured
    are marked NOT_STRUCTURED with the reason. Nothing is fabricated
    (Constitution Art. VI).
  * Future failures (the repo-rule applier) must emit all six elements
    structurally: new_pathway_entry() is the required shape.
"""

import json
import os
import subprocess

PATHWAY_ELEMENTS = ("CANDIDATE", "FAILURE_REASON", "EVIDENCE",
                    "ATTACK_RESULTS", "KILL_CONDITION", "CEMETERY")

PATHWAY_SCHEMA = {
    "CANDIDATE": "territory_id + mechanism_name + proposed_version — "
                 "what was generated and proposed",
    "FAILURE_REASON": "kill_reason (class) + why_it_failed (recorded "
                      "detail)",
    "EVIDENCE": "evidence_sources — the artifacts that document the "
                "failure",
    "ATTACK_RESULTS": "structured adversarial-attack outcomes that "
                      "contributed to (or were run against) the candidate; "
                      "legacy entries without structured results carry "
                      "state NOT_STRUCTURED honestly",
    "KILL_CONDITION": "the explicit condition under which the candidate "
                      "is dead (derived for legacy entries from the "
                      "recorded kill_reason / physical_constraint — "
                      "marked as derived, never invented)",
    "CEMETERY": "entry_id + append-only residency; the entry is the "
                "record, so removal is forbidden",
}


# ---------------------------------------------------------------------------
# per-entry pathway (re-presentation of recorded data — no invention)
# ---------------------------------------------------------------------------

def _kill_condition_of(entry: dict) -> dict:
    """Explicit kill condition: from the structured field when present;
    for legacy entries, re-presented from recorded fields and MARKED as
    a derivation."""
    if entry.get("kill_condition"):
        return {"value": entry["kill_condition"],
                "derivation": "recorded structured field"}
    parts = [str(entry.get("kill_reason") or "").strip()]
    pc = entry.get("physical_constraint")
    if pc:
        parts.append(f"physical constraint: {pc}")
    value = "; ".join(p for p in parts if p and p != "None")
    if not value:
        return {"value": None, "derivation": "NOT_RECORDED"}
    return {"value": value,
            "derivation": "re-presented from the recorded kill_reason "
                          "(+ physical_constraint where present) — "
                          "R374-6 schema, not new evidence"}


def _attack_results_of(entry: dict) -> dict:
    ar = entry.get("attack_results")
    if ar in (None, "", [], {}):
        narrative = " ".join(
            str(entry.get(k) or "") for k in
            ("why_it_failed", "what_to_avoid", "reusable_lesson"))
        had_attacks = "attack" in narrative.lower()
        return {
            "state": "NOT_STRUCTURED",
            "reason": (
                "legacy entry predates the structured attack-results "
                "field; " +
                ("attack narrative is embedded in why_it_failed — "
                 "re-presented there, not restructured (Art. VI)"
                 if had_attacks else
                 "no attack-stage result recorded for this entry — not "
                 "fabricated")),
        }
    return {"state": "STRUCTURED", "value": ar}


def entry_pathway(entry: dict) -> dict:
    """The six-element pathway of one cemetery entry, re-presented from
    recorded fields."""
    return {
        "CANDIDATE": {
            "territory_id": entry.get("territory_id"),
            "mechanism_name": entry.get("mechanism_name"),
            "proposed_version": entry.get("proposed_version"),
        },
        "FAILURE_REASON": {
            "kill_reason": entry.get("kill_reason"),
            "why_it_failed": entry.get("why_it_failed"),
        },
        "EVIDENCE": {
            "evidence_sources": entry.get("evidence_sources"),
        },
        "ATTACK_RESULTS": _attack_results_of(entry),
        "KILL_CONDITION": _kill_condition_of(entry),
        "CEMETERY": {
            "entry_id": entry.get("entry_id"),
            "append_only": True,
            "note": "the cemetery entry is the record; nothing is "
                    "deleted (CEO R374-6)",
        },
    }


def audit_entry_pathway(entry: dict) -> dict:
    """Mechanical completeness audit of one entry's pathway."""
    problems = []
    missing_elements = []
    cand = entry.get("pathway", {}).get("CANDIDATE", {})
    if not (cand.get("territory_id") and cand.get("mechanism_name")):
        problems.append("CANDIDATE incomplete")
        missing_elements.append("CANDIDATE")
    fr = entry.get("pathway", {}).get("FAILURE_REASON", {})
    if not (fr.get("kill_reason") or fr.get("why_it_failed")):
        problems.append("FAILURE_REASON absent")
        missing_elements.append("FAILURE_REASON")
    ev = entry.get("pathway", {}).get("EVIDENCE", {})
    if not ev.get("evidence_sources"):
        problems.append("EVIDENCE absent")
        missing_elements.append("EVIDENCE")
    ar = entry.get("pathway", {}).get("ATTACK_RESULTS", {})
    if not ar.get("state"):
        problems.append("ATTACK_RESULTS unclassified")
        missing_elements.append("ATTACK_RESULTS")
    kc = entry.get("pathway", {}).get("KILL_CONDITION", {})
    if not kc.get("value"):
        problems.append("KILL_CONDITION absent")
        missing_elements.append("KILL_CONDITION")
    cem = entry.get("pathway", {}).get("CEMETERY", {})
    if not cem.get("entry_id"):
        problems.append("CEMETERY entry_id absent")
        missing_elements.append("CEMETERY")
    return {
        "entry_id": entry.get("entry_id"),
        "elements_present": [e for e in PATHWAY_ELEMENTS
                             if e not in missing_elements],
        "problems": problems,
        "complete": not problems,
    }


# ---------------------------------------------------------------------------
# cemetery migration + audit
# ---------------------------------------------------------------------------


def _entry_chain_hash(entry: dict) -> str:
    """Deterministic content hash of an entry EXCLUDING chain fields."""
    import hashlib
    stripped = {k: v for k, v in entry.items()
                if k not in ("prev_entry_sha256",)}
    return hashlib.sha256(json.dumps(
        stripped, sort_keys=True, ensure_ascii=False, default=str).encode()
    ).hexdigest()


def _chain_backfill(cemetery: dict) -> None:
    """ONE-TIME internal hash-chain backfill (2026-08-30).

    Why: git-based append-only verification CANNOT detect deletion of
    UNCOMMITTED entries (found live when this cycle's 5 benchmark kills
    legitimately grew the cemetery between commits). Each entry now
    carries prev_entry_sha256 and the file carries chain_head_sha256 —
    any deletion, reordering or mid-file insertion breaks the chain.

    Idempotence is LAUNDERING-SAFE: when chain fields already exist they
    are left UNTOUCHED (a tampered file is never silently re-chained —
    Art. IX); verification lives in audit_cemetery.
    """
    entries = cemetery.get("entries", [])
    if not entries or all("prev_entry_sha256" in e for e in entries):
        # empty cemetery or fully chained: nothing to backfill; NEVER
        # recompute an existing chain
        if entries and "chain_head_sha256" not in cemetery:
            prev = None
            for e in entries:
                h = _entry_chain_hash(e)
                e.setdefault("prev_entry_sha256", prev)
                prev = h
            cemetery["chain_head_sha256"] = prev or ""
        return
    prev = None
    for e in entries:
        if "prev_entry_sha256" in e:
            prev = _entry_chain_hash(e)
            continue
        e["prev_entry_sha256"] = prev
        prev = _entry_chain_hash(e)
    cemetery["chain_head_sha256"] = prev or ""


def _chain_verify(cemetery: dict) -> dict:
    """Verify the internal chain: returns {valid, break_index, reason}."""
    entries = cemetery.get("entries", [])
    if not entries:
        return {"valid": True, "reason": "empty cemetery"}
    if "chain_head_sha256" not in cemetery or any(
            "prev_entry_sha256" not in e for e in entries):
        return {"valid": None,
                "reason": "chain not backfilled (run migrate_cemetery once)"}
    prev = None
    for i, e in enumerate(entries):
        if e.get("prev_entry_sha256") != prev:
            return {"valid": False, "break_index": i,
                    "reason": f"entry {i} prev_entry_sha256 mismatch "
                              f"(deletion/reorder/insertion detected)"}
        prev = _entry_chain_hash(e)
    head_ok = cemetery.get("chain_head_sha256") == prev
    return {"valid": head_ok, "reason": None if head_ok else
            "chain_head_sha256 mismatch (tail deletion detected)"}


def migrate_cemetery(cemetery: dict) -> dict:
    """Attach the six-element pathway to every entry IN PLACE (all
    original fields preserved verbatim; only the pathway sub-block is
    added). Deterministic — safe for byte-reproducible rebuilds."""
    for entry in cemetery.get("entries", []):
        if "pathway" not in entry:
            entry["pathway"] = entry_pathway(entry)
    _chain_backfill(cemetery)
    cemetery.setdefault("pathway_schema", {
        "schema": "R374_FAILED_CANDIDATE_PATHWAY",
        "elements": list(PATHWAY_ELEMENTS),
        "definitions": PATHWAY_SCHEMA,
        "append_only": True,
        "note": "pathway blocks are re-presentations of recorded fields "
                "(derivations marked); nothing fabricated (Art. VI)",
    })
    return cemetery


def audit_cemetery(cemetery: dict, engine_root: str) -> dict:
    """Full R374-6 audit: pathway completeness per entry + append-only
    verification against git history (nothing deleted)."""
    entries = cemetery.get("entries", [])
    per_entry = [audit_entry_pathway(e) for e in entries]
    ids_now = [e.get("entry_id") for e in entries]

    # append-only check against the git HEAD version of the cemetery
    removed, prev_count = [], None
    git_head_ids = None
    try:
        r = subprocess.run(
            ["git", "-C", engine_root, "show",
             "HEAD:MECHANISM_CEMETERY/CEMETERY.json"],
            capture_output=True, timeout=60)
        if r.returncode == 0:
            prev = json.loads(r.stdout.decode("utf-8"))
            prev_count = len(prev.get("entries", []))
            git_head_ids = [e.get("entry_id")
                            for e in prev.get("entries", [])]
            removed = [i for i in git_head_ids if i not in set(ids_now)]
    except Exception:
        git_head_ids = None  # no git history available (e.g. fresh clone
        # before first commit) — disclosed, not silently passed

    chain = _chain_verify(cemetery)
    complete = all(p["complete"] for p in per_entry)
    # append-only = BOTH (a) no committed deletion (git) AND (b) the
    # internal chain holds (catches UNCOMMITTED deletion — git cannot)
    git_ok = (git_head_ids is None) or (not removed and
                                        (prev_count or 0) <= len(entries))
    append_only_ok = git_ok and chain["valid"] is not False
    return {
        "schema": "R374_CEMETERY_PATHWAY_AUDIT",
        "entry_count": len(entries),
        "pathway_complete_entries": sum(1 for p in per_entry
                                        if p["complete"]),
        "incomplete_entries": [p["entry_id"] for p in per_entry
                               if not p["complete"]],
        "per_entry": per_entry,
        "append_only": {
            "checked_against": "git HEAD:MECHANISM_CEMETERY/CEMETERY.json"
                               if git_head_ids is not None else
                               "NOT_CHECKABLE (no git history at this "
                               "path)",
            "previous_entry_count": prev_count,
            "removed_entry_ids": removed,
            "nothing_deleted": append_only_ok,
            "internal_chain": chain,
        },
        "ok": complete and append_only_ok,
    }


# ---------------------------------------------------------------------------
# future failures: the required structural shape
# ---------------------------------------------------------------------------

def new_pathway_entry(*, entry_id, territory_id, mechanism_name,
                      proposed_version, kill_reason, why_it_failed,
                      evidence_sources, attack_results, kill_condition,
                      reusable_lesson=None, what_to_avoid=None,
                      epistemic_class=None) -> dict:
    """The six-element pathway shape every NEW cemetery entry must carry
    (used by the repo-rule applier). All six elements structural —
    legacy honesty markers are not permitted for new entries."""
    return {
        "entry_id": entry_id,
        "territory_id": territory_id,
        "mechanism_name": mechanism_name,
        "proposed_version": proposed_version,
        "kill_reason": kill_reason,
        "why_it_failed": why_it_failed,
        "evidence_sources": evidence_sources,
        "attack_results": attack_results,
        "kill_condition": kill_condition,
        "reusable_lesson": reusable_lesson,
        "what_to_avoid": what_to_avoid,
        "epistemic_class": epistemic_class,
        "pathway": {
            "CANDIDATE": {"territory_id": territory_id,
                          "mechanism_name": mechanism_name,
                          "proposed_version": proposed_version},
            "FAILURE_REASON": {"kill_reason": kill_reason,
                               "why_it_failed": why_it_failed},
            "EVIDENCE": {"evidence_sources": evidence_sources},
            "ATTACK_RESULTS": {"state": "STRUCTURED",
                               "value": attack_results},
            "KILL_CONDITION": {"value": kill_condition,
                               "derivation": "recorded structured field"},
            "CEMETERY": {"entry_id": entry_id, "append_only": True,
                         "note": "the cemetery entry is the record; "
                                 "nothing is deleted (CEO R374-6)"},
        },
    }
