"""discovery_fabric/engine/package_factory.py — E4/E10/E12 survivor -> buyer
package bridge + CEO Directives 1/5/6/7.

CEO E4: the discovery engine calls the SAME generator architecture that
produced technology-transfer-portfolio-15 (premium_package_factory/
templates/build_portfolio_v4.py per-package builders). Templates are NOT
recreated; the bridge converts a canonical invention specification +
engineering specification into the ArtifactRichDossier shape those builders
already consume, then renders the established buyer hierarchy:

    00_PACKAGE_README.pdf
    01_EXECUTIVE_TECHNOLOGY_BRIEF.pdf
    02_ENGINEERING_TECHNOLOGY_TRANSFER_DOSSIER.pdf
    03_BUYER_DECISION_CARD.pdf
    04_EVIDENCE_SUMMARY.pdf
    05_TRANSFER_MANIFEST.pdf
    PACKAGE_MANIFEST.json
    ENGINEERING_TRACEABILITY.json
    MATURITY_BASIS.json
    <short>.zip

CEO Directive 6 (NO MATERIAL TRUNCATION): the authoritative values live in
INVENTION_SPECIFICATION.json / ENGINEERING_SPECIFICATION.json (full text,
no slicing anywhere). The v4 builders receive a display VIEW in which only
fixed-width-table-bound strings are shortened — every such derivation goes
through the DisplayRegister (fields.py), whose full+display entries are
serialized into PACKAGE_MANIFEST.json so each package carries its own proof
that no authoritative value was used in truncated form. A register
violation fails the build (PackageBuildError).

CEO Directive 7 (COMPUTED MATURITY): MATURITY_BASIS.json is generated by
maturity.compute_maturity from the ACTUAL artifact state — the generic
blocker list is gone; blockers are the evaluated unsatisfied conditions of
the next ladder rung, each with its artifact evidence.

Status doctrine (Art. XXXVII/XXXVIII): every generated package declares
loop_verification_state=NONE and REAL_LOOP_VERIFIED=FALSE (derived state,
impossible to assign manually) and transfer_ready only when the computed
maturity reaches TRANSFER_READY. A package built from a rehearsal fixture
is additionally flagged SYNTHETIC_REHEARSAL=TRUE and must never leave the
development environment.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional

from .candidate import Candidate, sha256_obj, utc_now
from .engineering_spec import build_engineering_spec
from .fields import (DisplayRegister, PackageBuildError, build_display_view)
from .invention_spec import SPEC_FIELDS, build_invention_spec, tagged
from .maturity import compute_maturity

REPO_ROOT = Path(__file__).resolve().parents[2]
FACTORY_V4 = REPO_ROOT / "premium_package_factory" / "templates" / \
    "build_portfolio_v4.py"

PACKAGE_FILES = [
    "00_PACKAGE_README.pdf",
    "01_EXECUTIVE_TECHNOLOGY_BRIEF.pdf",
    "02_ENGINEERING_TECHNOLOGY_TRANSFER_DOSSIER.pdf",
    "03_BUYER_DECISION_CARD.pdf",
    "04_EVIDENCE_SUMMARY.pdf",
    "05_TRANSFER_MANIFEST.pdf",
]

# Directive 6: the ONLY permitted display shortenings — strings rendered
# inside fixed-width reportlab Table cells of the frozen v4 builders (raw
# strings in Table cells do not wrap). Every other string flows to the
# builders at FULL length (Paragraph surfaces wrap text). Each shortening
# is registered with its preserved full value.
TABLE_BOUND_DISPLAY_LIMITS = {
    "engineering_content.design_inputs[].input": 120,
    "engineering_content.design_inputs[].value": 220,
    "engineering_content.design_outputs[].description": 180,
    "engineering_content.engineering_core.failure_modes[].mode": 140,
    "engineering_content.engineering_core.failure_modes[].mechanism": 140,
    "engineering_content.engineering_core.failure_modes[].mitigation": 120,
    "engineering_content.failure_analysis[].mode": 140,
    "engineering_content.failure_analysis[].mechanism": 140,
    "engineering_content.failure_analysis[].mitigation": 120,
    "engineering_content.engineering_core.critical_parameters[].parameter": 140,
    "engineering_content.engineering_core.critical_parameters[].verification_requirement": 160,
    "engineering_content.verification_matrix[].requirement": 160,
    "engineering_content.verification_matrix[].method": 160,
    "engineering_content.verification_matrix[].acceptance": 140,
    "engineering_content.engineering_build_plan[].test_article": 120,
    "engineering_content.engineering_build_plan[].equipment": 100,
    "engineering_content.engineering_build_plan[].measurement": 140,
    "engineering_content.engineering_build_plan[].acceptance": 140,
    "engineering_content.engineering_build_plan[].acceptance_criterion": 140,
    "engineering_content.engineering_build_plan[].deliverable": 120,
    "engineering_content.bom[].description": 100,
    "engineering_content.bom[].verification": 100,
}


def _load_v4():
    """Load the frozen portfolio-v4 builder module by path. No state is
    mutated: the per-package builders are pure functions of (pi, d, op)."""
    spec = importlib.util.spec_from_file_location("engine_portfolio_v4",
                                                  FACTORY_V4)
    mod = importlib.util.module_from_spec(spec)
    import sys
    sys.modules["engine_portfolio_v4"] = mod
    spec.loader.exec_module(mod)
    return mod


def _sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _safe_slug(s: str, maxlen: int = 40) -> str:
    """Identifier slug for FOLDER naming only — not a content display field.
    The full technology name is preserved verbatim in PACKAGE_MANIFEST.json
    (technology_name) and in the invention specification."""
    slug = "".join(ch if ch.isalnum() else "_" for ch in s.lower()).strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return (slug or "technology")[:maxlen].strip("_")


# --------------------------------------------------------------------------
def survivor_to_canonical_package(
        spec: Dict[str, Any], eng: Dict[str, Any], env: Optional[Candidate],
        run_ctx: Dict[str, Any], rehearsal: bool = False) -> Dict[str, Any]:
    """Assemble the ArtifactRichDossier-shaped record + package-info entry
    for the frozen v4 builders (E4 reuse). Directive 6: evidence abstracts
    flow at FULL length (the evidence-summary Paragraph wraps)."""
    problem = (spec.get("problem") or {}).get("value") or {}
    mech = (spec.get("mechanism") or {}).get("value") or {}
    invention_id = (spec.get("invention_id") or {}).get("value", "inv:unknown")
    short = _safe_slug(problem.get("device") or invention_id.split(":")[-1])

    # Evidence-bound external source list (E5): custodied evidence first,
    # standards candidates second — each item carries source + snippet keys
    # the v4 evidence-summary builder expects.
    ext: List[Dict[str, Any]] = []
    for e in (env.evidence if env else []) or []:
        ext.append({
            "source_title": e.get("title", ""),
            "source": e.get("source_uri") or e.get("doi") or "",
            "source_snippet": e.get("abstract") or "",   # FULL, Directive 6
            "evidence_id": e.get("id"),
            "content_hash": e.get("content_hash"),
            "epistemic_class": "SOURCE_FACT (custodied evidence)"})
    for s in eng.get("external_engineering_precedent", []):
        ext.append({
            "source_title": s.get("precedent", ""),
            "source": "standard reference — verify applicability",
            "source_snippet": "candidate standard; applicability NOT "
                              "verified (Art. II)",
            "epistemic_class": "EXTERNAL_PRECEDENT_CANDIDATE"})

    # pi: the per-package identity the v4 builders expect
    n = run_ctx.get("package_number") or "90"
    pi = {
        "num": n,
        "pkg_id": invention_id,
        "short": short,
        "name": mech.get("intervention", "") or
                f"Engine-discovered invention {invention_id}",
        "problem": problem.get("failure", ""),
        "mechanism": mech.get("mechanism", ""),
        "buyer_type": (problem.get("target_buyer")
                       or "domain-appropriate technology buyer (to be "
                          "identified by portfolio owner)"),
        "kill_if": _kill_condition(spec),
    }
    dossier = {
        "package_id": invention_id,
        "view_type": "ENGINE_GENERATED_ARTIFACT_RICH",
        "engineering_content": eng,
        "_provenance": {
            "run_id": run_ctx.get("run_id"),
            "final_envelope_hash": (env.envelope_hash() if env else None),
            "invention_spec_hash": spec.get("_spec_hash"),
            "rehearsal": rehearsal,
            "loop_verification_state": "NONE",
            "real_loop_verified": False,
            "transfer_ready": False,
            "generated_at": utc_now()},
    }
    return {"pi": pi, "dossier": dossier, "external_sources": ext}


def _kill_condition(spec: Dict[str, Any]) -> str:
    """Kill condition = the candidate's own recorded falsification path.
    No new thresholds are invented here (Art. XXVII)."""
    ke = (spec.get("killer_experiment") or {}).get("value") or {}
    sel = ke.get("selected")
    name = sel if isinstance(sel, str) else (sel or {}).get("name", "")
    return (f"killer experiment fails: {name or 'NOT ESTABLISHED'} "
            "(pre-registered pass/fail required before any transfer)")


# --------------------------------------------------------------------------
def build_traceability(spec: Dict[str, Any], eng: Dict[str, Any],
                       pkg: Dict[str, Any],
                       env: Optional[Candidate]) -> Dict[str, Any]:
    """E12 ENGINEERING_TRACEABILITY.json — computed from STRUCTURAL links.

    Chains: PACKAGE_CLAIM -> INVENTION_FIELD -> CANDIDATE_STAGE ->
    EVIDENCE_ID -> SOURCE -> HASH. Structural, not keyword-based.
    """
    graph = eng.get("design_graph") or {}
    ev_index = (spec.get("_evidence_index") or {})
    chains: List[Dict[str, Any]] = []
    # design-input chains
    for d in eng.get("design_inputs", []):
        chains.append({
            "chain_type": "DESIGN_INPUT",
            "node_id": d["id"],
            "invention_field": "problem" if "problem.json" in
                               (d.get("evidence_refs") or []) else "mechanism",
            "candidate_stage": d.get("source", "MODELLED (LLM synthesis)"),
            "evidence_ids": d.get("evidence_refs", []),
            "source": ev_index.get((d.get("evidence_refs") or [None])[0], {})
                      .get("source_uri", "engine-generated (structural)"),
            "hash": sha256_obj(d),
            "linked": bool(d.get("parent_ids"))})
    # design-output chains
    for d in eng.get("design_outputs", []):
        chains.append({
            "chain_type": "DESIGN_OUTPUT", "node_id": d["id"],
            "invention_field": "engineering_parameters",
            "candidate_stage": d.get("basis", "ENGINEERING_PROPOSED"),
            "evidence_ids": [],
            "parent_ids": d.get("parent_ids", []),
            "hash": sha256_obj(d),
            "linked": bool(d.get("parent_ids"))})
    # failure mode chains — every row carries its explicit design-graph id;
    # UNTRACEABLE is reserved for rows whose ORIGIN is unknown (Art. VI),
    # while NOT_LINKED merely means no VF targets the FM yet (recorded as a
    # design-graph gap, not hidden)
    for i, f in enumerate(eng.get("failure_analysis", [])):
        basis = f.get("evidence", "UNKNOWN")
        origin_known = bool(basis) and not basis.startswith("UNKNOWN")
        linked = f.get("verification", "NOT_LINKED") not in (
            "NOT_LINKED", None, "")
        chains.append({
            "chain_type": "FAILURE_MODE",
            "node_id": f.get("graph_id", f"FM-?{i}"),
            "invention_field": "failure_modes",
            "candidate_stage": basis,
            "evidence_ids": [],
            "hash": sha256_obj(f),
            "linked": linked,
            "untraceable": not origin_known})
    # verification chains
    for v in eng.get("verification_matrix", []):
        chains.append({
            "chain_type": "VERIFICATION", "node_id": v["id"],
            "invention_field": "killer_experiment",
            "candidate_stage": "KILLER_EXPERIMENT",
            "evidence_ids": [],
            "hash": sha256_obj(v),
            "linked": True, "result": v.get("result", "NOT_TESTED")})

    eq_integrity = {
        "equations_total": len(eng.get("engineering_core", {})
                               .get("governing_model", {}).get("equations", [])),
        "numeric_values_emitted": 0,
        "rule": "no numeric value may be emitted without SOURCE_FACT or "
                "COMPUTED inputs (Art. XXVII); generator emits SYMBOLIC ONLY",
        "all_symbolic": True}
    number_provenance = {
        "policy": "every number in this package is either a content hash, a "
                  "count, or an engine score; NO physical parameter values "
                  "exist because no measurement exists",
        "violations": []}
    di_do = {
        "method": "structural parent_ids (explicit IDs), NOT keyword matching",
        "d_inputs": len(eng.get("design_inputs", [])),
        "d_outputs": len(eng.get("design_outputs", [])),
        "unlinked_outputs": [d["id"] for d in eng.get("design_outputs", [])
                             if not d.get("parent_ids")]}
    passed = (graph.get("integrity", {}).get("passed", False)
              and not number_provenance["violations"])
    untraceable_fields = [c["node_id"] for c in chains
                          if c.get("untraceable")]
    return {
        "package_id": (pkg["pi"]["pkg_id"]),
        "traceability_chains": chains,
        "equation_integrity": eq_integrity,
        "number_provenance": number_provenance,
        "di_do_consistency": di_do,
        "design_graph_integrity": graph.get("integrity"),
        "gaps": graph.get("gaps", []),
        "evidence_index": {
            k: {"title": v.get("title"), "content_hash": v.get("content_hash"),
                "source_uri": v.get("source_uri")}
            for k, v in ev_index.items()},
        "provenance_chain_template": ("PACKAGE_CLAIM -> INVENTION_FIELD -> "
                                      "CANDIDATE_STAGE -> EVIDENCE_ID -> "
                                      "SOURCE -> HASH"),
        "untraceable_engineering_fields": untraceable_fields,
        "issues": graph.get("integrity", {}).get("problems", []),
        "passed": passed,
        "checked_at": utc_now(),
    }


def build_maturity_basis(spec: Dict[str, Any], eng: Dict[str, Any],
                         data: Dict[str, Any],
                         pkg: Optional[Dict[str, Any]] = None,
                         env: Optional[Candidate] = None,
                         package_report: Optional[Dict[str, Any]] = None
                         ) -> Dict[str, Any]:
    """Directive 7: MATURITY_BASIS.json computed from the ACTUAL generated
    artifact state. No generic blocker injection — blockers are the
    evaluated unsatisfied conditions of the next ladder rung."""
    computed = compute_maturity(spec, eng, env=env,
                                package_report=package_report)
    core = eng.get("engineering_core", {})
    gm = core.get("governing_model", {})
    counts = computed["counts"] | {
        "governing_model_evidence_count": len(gm.get("equations", []))}
    return {
        "package_id": (spec.get("invention_id") or {}).get("value"),
        "technology_maturity": computed["technology_maturity"],
        "builder_view_maturity": data.get("maturity"),
        "basis": computed["basis"],
        "maturity_ladder": computed["maturity_ladder"],
        "rung_evaluations": computed["rung_evaluations"],
        "next_rung": computed["next_rung"],
        "known_blockers": computed["known_blockers"],
        "governing_model_evidence_ids": [e["equation_id"]
                                         for e in gm.get("equations", [])],
        "design_input_evidence_ids": [d["id"] for d in
                                      eng.get("design_inputs", [])],
        "design_output_evidence_ids": [d["id"] for d in
                                       eng.get("design_outputs", [])],
        "failure_analysis_evidence_ids": [f"FM-{i+1:03d}" for i in
                                          range(len(eng.get("failure_analysis",
                                                            [])))],
        "build_plan_evidence_ids": [w["work_package"] for w in
                                    eng.get("engineering_build_plan", [])],
        "verification_evidence_ids": [v["id"] for v in
                                      eng.get("verification_matrix", [])],
        "external_evidence_ids": [e.get("evidence_id")
                                  for e in (pkg or {}).get("external_sources", [])
                                  if e.get("evidence_id")],
        "counts": counts,
        "loop_verification_state": computed["loop_verification_state"],
        "real_loop_verified": computed["real_loop_verified"],
        "transfer_ready": computed["transfer_ready"],
        "computed_at": computed["computed_at"],
    }


# --------------------------------------------------------------------------
def generate_buyer_package(
        out_dir: str, spec: Dict[str, Any], eng: Dict[str, Any],
        env: Optional[Candidate], run_ctx: Dict[str, Any],
        rehearsal: bool = False) -> Dict[str, Any]:
    """E10: SURVIVING INVENTION -> DOWNLOAD/<nn>_<short>/ + .zip.
    Reuses the frozen v4 builders through a registered display view
    (Directive 6) and emits computed maturity (Directive 7). Returns a
    report with every file+hash and an explicit fail list (missing link =
    loud failure, E11 contract)."""
    out = Path(out_dir)
    register = DisplayRegister()
    pkg = survivor_to_canonical_package(spec, eng, env, run_ctx,
                                        rehearsal=rehearsal)
    v4 = _load_v4()
    pi, dossier = pkg["pi"], pkg["dossier"]

    # Directive 6: the builders see a display VIEW; authoritative full text
    # stays in this module's `eng` (written to ENGINEERING_SPECIFICATION.json
    # by the caller) and in the register serialized below.
    dossier_view = build_display_view(dossier, register,
                                      TABLE_BOUND_DISPLAY_LIMITS)
    reg_violations = register.violations()
    if reg_violations:
        raise PackageBuildError(
            "display register violation (Directive 6): " +
            "; ".join(reg_violations))

    data = v4.get_data(dossier_view, pi)

    folder = out / "DOWNLOAD" / f"{pi['num']}_{pi['short']}"
    folder.mkdir(parents=True, exist_ok=True)

    # render the 6 canonical PDFs with the frozen builders
    rendered: List[Dict[str, Any]] = []
    failed: List[Dict[str, Any]] = []
    jobs = [
        ("00_PACKAGE_README.pdf", lambda p: v4.build_readme(pi, data, p)),
        ("01_EXECUTIVE_TECHNOLOGY_BRIEF.pdf",
         lambda p: v4.build_exec_brief(pi, dossier_view, p)),
        ("02_ENGINEERING_TECHNOLOGY_TRANSFER_DOSSIER.pdf",
         lambda p: v4.build_dossier(pi, dossier_view, p)),
        ("03_BUYER_DECISION_CARD.pdf",
         lambda p: v4.build_buyer_card(pi, dossier_view, p)),
        ("04_EVIDENCE_SUMMARY.pdf",
         lambda p: v4.build_evidence_summary(pi, dossier_view, p)),
        ("05_TRANSFER_MANIFEST.pdf",
         lambda p: v4.build_transfer_manifest(pi, dossier_view, p)),
    ]
    for fname, fn in jobs:
        path = folder / fname
        try:
            fn(str(path))
            if not path.exists() or path.stat().st_size == 0:
                raise RuntimeError("builder produced no bytes")
            rendered.append({"file": fname,
                             "sha256": _sha256_file(path),
                             "bytes": path.stat().st_size})
        except Exception as exc:  # noqa: BLE001 — recorded, fails the run
            failed.append({"file": fname,
                           "error": f"{type(exc).__name__}: {exc}"})

    # traceability + computed maturity + manifest
    trace = build_traceability(spec, eng, pkg, env)
    trace_path = folder / "ENGINEERING_TRACEABILITY.json"
    trace_path.write_text(json.dumps(trace, indent=2, ensure_ascii=False))

    maturity = build_maturity_basis(spec, eng, data, pkg, env=env,
                                    package_report=None)
    maturity_path = folder / "MATURITY_BASIS.json"
    maturity_path.write_text(json.dumps(maturity, indent=2,
                                        ensure_ascii=False))

    discipline_note = (
        "SYNTHETIC REHEARSAL — generated from a recorded fixture envelope; "
        "NOT a real discovery run; must not be shown to buyers"
        if rehearsal else
        "Generated end-to-end by discovery_fabric.engine from a real "
        "engine run envelope")

    manifest = {
        "portfolio_number": pi["num"],
        "package_id": pi["pkg_id"],
        "technology_name": pi["name"],          # FULL name (Directive 6)
        "package_version": "1.1",
        "generator": "discovery_fabric.engine.package_factory "
                     "(E4/E10 + Directives 1/5/6/7)",
        "generator_basis": "premium_package_factory/templates/"
                           "build_portfolio_v4.py builders (frozen, reused)",
        "technology_maturity": maturity["technology_maturity"],
        "technology_maturity_basis": "computed (see MATURITY_BASIS.json)",
        "builder_view_maturity": data["maturity"],
        "dossier_maturity": "COMPLETE_FOR_CURRENT_STAGE",
        "transfer_posture": data["posture"],
        "loop_verification_state": maturity["loop_verification_state"],
        "real_loop_verified": maturity["real_loop_verified"],
        "transfer_ready": maturity["transfer_ready"],
        "synthetic_rehearsal": rehearsal,
        "discipline_note": discipline_note,
        "display_register": register.to_json(),
        "provenance": {
            "run_id": run_ctx.get("run_id"),
            "final_envelope_hash": (env.envelope_hash() if env else None),
            "invention_spec_hash": spec.get("_spec_hash"),
            "candidate_stages": [e["stage"] for e in
                                 (env.stage_log if env else [])]},
        "files": rendered,
        "traceability_passed": trace["passed"],
        "untraceable_engineering_fields":
            trace["untraceable_engineering_fields"],
        "external_evidence_count": len(pkg["external_sources"]),
        "engineering_artifact_count": len(eng.get(
            "engineering_build_plan", [])),
        "generated_at": utc_now(),
    }
    (folder / "PACKAGE_MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False))

    # zip mirrors the established hierarchy
    zip_path = out / "DOWNLOAD" / f"{pi['num']}_{pi['short']}.zip"
    if not failed:
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in sorted(folder.iterdir()):
                zf.write(f, f"{folder.name}/{f.name}")

    # E11 contract: report missing links loudly
    expected = PACKAGE_FILES + ["PACKAGE_MANIFEST.json",
                                "ENGINEERING_TRACEABILITY.json",
                                "MATURITY_BASIS.json"]
    present = {r["file"] for r in rendered} | {
        "PACKAGE_MANIFEST.json", "ENGINEERING_TRACEABILITY.json",
        "MATURITY_BASIS.json"}
    missing = [f for f in expected if f not in present]
    if not missing and not failed and zip_path.exists():
        zip_ok = True
        with zipfile.ZipFile(zip_path) as zf:
            zip_ok = zf.testzip() is None
        if not zip_ok:
            failed.append({"file": zip_path.name, "error": "zip test failed"})
    missing.extend(f["file"] for f in failed)

    return {
        "folder": str(folder),
        "zip": str(zip_path) if zip_path.exists() else None,
        "rendered": rendered,
        "failed": failed,
        "missing_links": missing,
        "complete": not missing,
        "maturity": maturity["technology_maturity"],
        "posture": data["posture"],
        "traceability_passed": trace["passed"],
        "display_register": register.to_json(),
    }
